# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('TIN', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('display_name', models.CharField(blank=True, max_length=20, null=True)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('social_id', models.CharField(blank=True, max_length=255)),
                ('login_type', models.CharField(blank=True, max_length=10, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_photo', models.ImageField(upload_to='./static/media/profile_pics')),
                ('id_photo', models.ImageField(blank=True, upload_to='./static/media/ID_PHOTOS')),
                ('approved_as_seller', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
